# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PicksumAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PicksumAPI
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'ReachabilitySwift', '~> 5.0.0'
  pod 'SDWebImage'
  pod 'AlamofireObjectMapper', '~> 5.2.0'

end
